Match User wbdprepare
    ForceCommand /usr/local/libexec/wbd-deployment/wbd-deploy-gateway prepare
    DisableForwarding yes
    PermitTTY no
    X11Forwarding no

Match User wbdswitch
    ForceCommand /usr/local/libexec/wbd-deployment/wbd-deploy-gateway switch
    DisableForwarding yes
    PermitTTY no
    X11Forwarding no
