export type ControlRecordType = "organizations" | "opportunities" | "commitments" | "actions" | "effort-observations";

interface SourceHealth { sourceId: string; status: "HEALTHY" | "STALE" | "FAILED" | "UNKNOWN"; coverage: "COMPLETE" | "PARTIAL" | "UNKNOWN"; impact: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL"; lastKnownGoodAt: string | null }
interface BaseRecord { id: string; revision: number; sourceHealthId: string; confirmedBy: string; createdAt: string; updatedAt: string }
export interface ControlOrganization extends BaseRecord { name: string; relationshipType: string; status: string; reviewedAt: string; sourceRefs: string[] }
export interface ControlOpportunity extends BaseRecord { organizationId: string; title: string; problemOrOpportunity: string; status: string; valueType: string; expectedOneOffRevenue: number | null; expectedMrr: number | null; proposalStatus: string; evidenceRefs: string[]; nextReviewAt: string; ownerActionId: string | null }
export interface ControlCommitment extends BaseRecord { organizationId: string; status: string; contractedMrr: number | null; startsAt: string | null; endsAt: string | null; renewalReviewAt: string | null; responsibilities: { description: string; responsibleParty: string }[]; sourceRefs: string[] }
export interface ControlAction extends BaseRecord { subjectType: string; subjectId: string; title: string; reasonDonovanNeeded: string; status: string; priority: string; dueAt: string | null; completedAt: string | null; sourceRefs: string[] }
export interface ControlEffort extends BaseRecord { organizationId: string; serviceCommitmentId: string | null; timeClass: string; category: string; minutes: number; context: string | null; capturedAt: string; status: string; sourceRefs: string[] }
export interface ControlView { schemaVersion: 1; organizations: ControlOrganization[]; opportunities: ControlOpportunity[]; serviceCommitments: ControlCommitment[]; ownerActions: ControlAction[]; effortObservations: ControlEffort[]; sourceHealth: SourceHealth[]; revision: number; releaseId: string }
export interface ControlOverview {
  revision: number;
  reliability: { status: "BETROUWBAAR" | "GEDEELTELIJK BETROUWBAAR" | "ONVOLDOENDE BRONDEKKING"; blockers: { sourceId: string; status: string; coverage: string; impact: string; message: string; lastKnownGoodAt: string | null }[]; noAttentionNeeded: boolean };
  attention: { kind: string; id: string; title: string; reason?: string; priority: string; dueAt: string | null }[];
  opportunities: (ControlOpportunity & { organizationName: string; ownerAction: ControlAction | null })[];
  company: { activeCommitments: number; confirmedContractedMrr: number | null; recurringMinutes: number | null; mrrPerRecurringHour: number | null; evidenceStatus: "SUFFICIENT" | "INSUFFICIENT"; period: string };
  responsibilityExceptions: { id: string; organizationName: string; renewalReviewAt: string | null; responsibilities: { description: string; responsibleParty: string }[]; sourceStatus: string }[];
  nextBestAction: { id: string; title: string; reason: string; priority: string; dueAt: string | null } | null;
  nextBestActionStatus: "SUPPORTED" | "INSUFFICIENT_EVIDENCE";
  capabilitiesPath: string;
}

interface PromotionEvidence { source: string; date: string; summary: string }
export interface PromotionProposal {
  id: string; operation: "CREATE" | "UPDATE" | "MATCH"; canonicalType: "ORGANIZATION" | "OPPORTUNITY" | "OWNER_ACTION";
  title: string; summary: string; confidence: string; uncertainty: string; evidence: PromotionEvidence[];
  allowedAdjustments: string[]; requiredHumanFields?: string[]; status: "READY" | "WAITING" | "BLOCKED" | "REVIEWED"; message: string | null;
  reviewed: { decision: "ACCEPT" | "ADJUST" | "REJECT"; reviewedAt: string } | null;
  match?: { id: string; name: string; revision: number } | null;
}
export interface PromotionView { schemaVersion: 1; revision: number; releaseId: string; proposals: PromotionProposal[] }

const esc = (value: unknown): string => String(value ?? "").replace(/[&<>'"]/gu, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character]!);
const euro = (value: number | null): string => value === null ? "ONBEKEND" : new Intl.NumberFormat("nl-NL", { style: "currency", currency: "EUR" }).format(value);
const dateLabel = (value: string | null): string => value ? new Intl.DateTimeFormat("nl-NL", { day: "numeric", month: "short", year: "numeric" }).format(new Date(value)) : "Geen datum";
const dateInput = (): string => new Date().toISOString().slice(0, 10);
const options = (values: readonly string[], selected?: string): string => values.map((value) => `<option value="${esc(value)}"${value === selected ? " selected" : ""}>${esc(value.replaceAll("_", " "))}</option>`).join("");

function organizationOptions(control: ControlView): string {
  return control.organizations.filter(({ status }) => status !== "ARCHIVED").map(({ id, name }) => `<option value="${esc(id)}">${esc(name)}</option>`).join("");
}

function actionSubjectOptions(control: ControlView): string {
  return [
    ...control.organizations.filter(({ status }) => status !== "ARCHIVED").map(({ id, name }) => `<option value="ORGANIZATION|${esc(id)}">Organisatie · ${esc(name)}</option>`),
    ...control.opportunities.map(({ id, title }) => `<option value="OPPORTUNITY|${esc(id)}">Kans · ${esc(title)}</option>`),
    ...control.serviceCommitments.map(({ id, organizationId }) => `<option value="SERVICE_COMMITMENT|${esc(id)}">Afspraak · ${esc(control.organizations.find(({ id: candidate }) => candidate === organizationId)?.name ?? id)}</option>`),
  ].join("");
}

function organizationCards(control: ControlView): string {
  return control.organizations.filter(({ status }) => status !== "ARCHIVED").map((organization) => {
    const opportunities = control.opportunities.filter(({ organizationId }) => organizationId === organization.id).length;
    const commitments = control.serviceCommitments.filter(({ organizationId }) => organizationId === organization.id && status !== "ENDED").length;
    const actions = control.ownerActions.filter(({ subjectType, subjectId, status }) => status === "OPEN" && subjectType === "ORGANIZATION" && subjectId === organization.id).length;
    return `<article class="wbd-organization-card"><div><span>${esc(organization.relationshipType.replaceAll("_", " "))}</span><h3>${esc(organization.name)}</h3><p>${organization.status === "UNKNOWN" ? "Actuele status is nog niet bevestigd." : `Status: ${esc(organization.status)}`}</p></div><dl><div><dt>Kansen</dt><dd>${opportunities}</dd></div><div><dt>Afspraken</dt><dd>${commitments}</dd></div><div><dt>Acties</dt><dd>${actions}</dd></div></dl></article>`;
  }).join("") || '<p class="wbd-control-empty">Nog geen bevestigde organisaties.</p>';
}

const sourceMeaning: Record<string, string> = {
  "wbd-owner-confirmed-organizations": "Organisaties nog niet volledig bekend",
  "wbd-owner-confirmed-opportunities": "Commerciële kansen nog niet volledig bekend",
  "wbd-owner-confirmed-commitments": "Recurring afspraken en verantwoordelijkheden nog niet volledig bekend",
  "wbd-owner-confirmed-actions": "Acties voor Donovan nog niet volledig bekend",
  "wbd-owner-confirmed-effort": "Recurring Donovan-tijd nog onvoldoende waargenomen",
};

function promotionAdjustFields(proposal: PromotionProposal): string {
  if (proposal.canonicalType === "ORGANIZATION") return `<label>Naam<input name="name" value="${esc(proposal.title)}" maxlength="160" required></label><label>Relatie<select name="relationshipType">${options(["CUSTOMER", "PROSPECT", "PARTNER"], "CUSTOMER")}</select></label><label>Actuele status<select name="status">${options(["UNKNOWN", "ACTIVE", "INACTIVE"], proposal.id.includes("bij-cees") ? "UNKNOWN" : "ACTIVE")}</select></label>`;
  if (proposal.canonicalType === "OPPORTUNITY") return `<label>Titel<input name="title" value="${esc(proposal.title)}" maxlength="180" required></label><label>Kans of probleem<textarea name="problemOrOpportunity" maxlength="1200" required>${esc(proposal.summary)}</textarea></label><label>Status<select name="status">${options(["OPEN", "ON_HOLD"], "OPEN")}</select></label><label>Wanneer opnieuw beoordelen?<input name="nextReviewAt" type="date" required></label>`;
  return `<label>Titel<input name="title" value="${esc(proposal.title)}" maxlength="200" required></label><label>Waarom ben jij nodig?<textarea name="reasonDonovanNeeded" maxlength="800" required>${esc(proposal.summary)}</textarea></label><label>Hoe belangrijk is dit?<select name="priority" required><option value="">Kies zelf</option>${options(["CRITICAL", "HIGH", "MEDIUM", "LOW"])}</select></label><label>Deadline (optioneel)<input name="dueAt" type="date"></label>`;
}

function promotionCards(promotions: PromotionView): string {
  return promotions.proposals.map((proposal) => {
    const reviewed = proposal.status === "REVIEWED";
    const ready = proposal.status === "READY";
    const incomplete = Boolean(proposal.requiredHumanFields?.length);
    return `<article class="wbd-promotion" data-status="${esc(proposal.status)}"><header><div><span>${proposal.operation === "MATCH" ? "Bestaande waarheid herkennen" : "Gevonden WBD-context"}</span><h3>${esc(proposal.title)}</h3></div><strong>${reviewed ? esc(proposal.reviewed?.decision ?? "BEOORDEELD") : ready ? "JOUW BESLISSING" : esc(proposal.status)}</strong></header><p>${esc(proposal.summary)}</p>${proposal.match ? `<p class="wbd-promotion__match">Bestaand record: ${esc(proposal.match.name)} — dit wordt geen nieuwe Organization.</p>` : ""}<p class="wbd-promotion__uncertainty">${esc(proposal.uncertainty)}</p>
      ${ready ? `<div class="wbd-promotion__actions">${incomplete ? '<button type="button" disabled title="Maak eerst de menselijke betekenis af">Bevestigen</button>' : `<button type="button" data-promotion-review="${esc(proposal.id)}" data-decision="ACCEPT">Bevestigen</button>`}<button type="button" data-promotion-toggle="${esc(proposal.id)}">Aanpassen</button><button type="button" data-promotion-review="${esc(proposal.id)}" data-decision="REJECT">Afwijzen</button></div><form class="wbd-promotion__adjust" data-promotion-adjust="${esc(proposal.id)}" hidden>${promotionAdjustFields(proposal)}<button type="submit">Aanpassen en bevestigen</button></form>` : `<p class="wbd-promotion__state">${esc(proposal.message ?? "Dit voorstel is beoordeeld.")}</p>`}
      <details><summary>Waarom weten we dit?</summary><p>Vertrouwen: ${esc(proposal.confidence)}. Dit blijft een voorstel totdat Donovan beslist.</p>${proposal.evidence.map((item) => `<article><time datetime="${esc(item.date)}">${esc(item.date)}</time><strong>${esc(item.summary)}</strong><small>${esc(item.source)}</small></article>`).join("")}</details></article>`;
  }).join("");
}

function recordForms(control: ControlView): string {
  const why = '<label>Waarom leggen we dit vast?<textarea name="sourceRefs" required placeholder="Korte menselijke bron of beslissing"></textarea></label>';
  return `<details class="wbd-control-fallback"><summary>Handmatig vastleggen (beheer)</summary><section class="wbd-control-capture"><header><p class="wbd-owner-eyebrow">Fallback</p><h2>Alleen wanneer een voorstel ontbreekt</h2><p>Technische brondekking en provenance worden door Workspace beheerd; hier bevestig je alleen bedrijfsbetekenis.</p></header><div class="wbd-control-capture__grid">
    <details><summary>Organisatie</summary><form data-control-form="organizations"><label>Naam<input name="name" required maxlength="160"></label><label>Relatie<select name="relationshipType">${options(["CUSTOMER", "PROSPECT", "PARTNER"], "PROSPECT")}</select></label><label>Status<select name="status">${options(["ACTIVE", "INACTIVE", "UNKNOWN"], "UNKNOWN")}</select></label><label>Beoordeeld op<input name="reviewedAt" type="date" value="${dateInput()}" required></label>${why}<button type="submit">Bevestigen</button></form></details>
    <details><summary>Commerciële kans</summary><form data-control-form="opportunities"><label>Organisatie<select name="organizationId">${organizationOptions(control)}</select></label><label>Titel<input name="title" required maxlength="180"></label><label>Kans of probleem<textarea name="problemOrOpportunity" required maxlength="1200"></textarea></label><label>Status<select name="status">${options(["OPEN", "ON_HOLD", "WON", "LOST"], "OPEN")}</select></label><label>Waardetype<select name="valueType">${options(["UNKNOWN", "ONE_OFF", "MRR", "MIXED"], "UNKNOWN")}</select></label><label>Eenmalige omzet €<input name="expectedOneOffRevenue" type="number" min="0" step="0.01"></label><label>Verwachte MRR €<input name="expectedMrr" type="number" min="0" step="0.01"></label><label>Voorstelstatus<select name="proposalStatus">${options(["NONE", "DRAFT", "SENT", "ACCEPTED", "DECLINED", "UNKNOWN"], "NONE")}</select></label><label>Volgende review<input name="nextReviewAt" type="date" required></label>${why}<button type="submit">Bevestigen</button></form></details>
    <details><summary>Serviceafspraak</summary><form data-control-form="commitments"><label>Organisatie<select name="organizationId">${organizationOptions(control)}</select></label><label>Status<select name="status">${options(["ACTIVE", "PAUSED", "UNKNOWN", "ENDED"], "UNKNOWN")}</select></label><label>Gecontracteerde MRR €<input name="contractedMrr" type="number" min="0" step="0.01" placeholder="Leeg = onbekend"></label><label>Start<input name="startsAt" type="date"></label><label>Einde<input name="endsAt" type="date"></label><label>Renewal-review<input name="renewalReviewAt" type="date"></label><label>Verantwoordelijkheid<textarea name="responsibilityDescription" required maxlength="600"></textarea></label><label>Verantwoordelijke partij<select name="responsibleParty">${options(["WBD", "CUSTOMER", "SHARED", "EXTERNAL_PROVIDER"], "SHARED")}</select></label>${why}<button type="submit">Vastleggen</button></form></details>
    <details><summary>Actie voor Donovan</summary><form data-control-form="actions"><label>Onderwerp<select name="subject">${actionSubjectOptions(control)}</select></label><label>Titel<input name="title" required maxlength="200"></label><label>Waarom ben jij nodig?<textarea name="reasonDonovanNeeded" required maxlength="800"></textarea></label><label>Prioriteit<select name="priority">${options(["HIGH", "MEDIUM", "LOW", "CRITICAL"], "MEDIUM")}</select></label><label>Deadline<input name="dueAt" type="date"></label>${why}<button type="submit">Vastleggen</button></form></details>
    <details><summary>Inspanning</summary><form data-control-form="effort-observations"><label>Organisatie<select name="organizationId">${organizationOptions(control)}</select></label><label>Tijdklasse<select name="timeClass">${options(["RECURRING_SERVICE", "SALES", "IMPLEMENTATION"], "RECURRING_SERVICE")}</select></label><label>Categorie<select name="category">${options(["SUPPORT", "CUSTOMER_CONTACT", "INCIDENT", "OPERATIONS", "REVIEW", "CODEX_DIRECTION"], "SUPPORT")}</select></label><fieldset class="wbd-effort-minutes"><legend>Minuten</legend>${[5, 15, 30, 60].map((minutes) => `<button type="button" data-effort-minutes="${minutes}" aria-pressed="${minutes === 15}">${minutes} min</button>`).join("")}<input name="minutes" type="hidden" value="15"></fieldset><label>Context<input name="context" maxlength="500"></label><input name="sourceRefs" type="hidden" value="Handmatige tijdwaarneming Donovan"><button type="submit">Registreren</button></form></details>
  </div><p class="wbd-control-message" data-control-message role="status"></p></section></details>`;
}

export function renderControlHome(topbar: string, control: ControlView, overview: ControlOverview, promotions: PromotionView): string {
  const reliabilityTone = overview.reliability.status === "BETROUWBAAR" ? "healthy" : overview.reliability.status === "GEDEELTELIJK BETROUWBAAR" ? "partial" : "blocked";
  const attention = overview.attention.length ? overview.attention.map((item) => `<article class="wbd-control-row"><div><span>${esc(item.kind.replaceAll("_", " "))} · ${esc(item.priority)}</span><strong>${esc(item.title)}</strong>${item.reason ? `<p>${esc(item.reason)}</p>` : ""}<small>${item.dueAt ? `Uiterlijk ${esc(dateLabel(item.dueAt))}` : "Geen deadline"}</small></div>${item.kind === "OWNER_ACTION" ? `<button type="button" data-complete-action="${esc(item.id)}">Afronden</button>` : ""}</article>`).join("") : `<p class="wbd-control-empty">${overview.reliability.noAttentionNeeded ? "Geen bekende actie nodig binnen gezonde en complete bronnen." : "Geen bevestigde acties, maar de brondekking staat nog geen stilteclaim toe."}</p>`;
  const opportunities = overview.opportunities.length ? overview.opportunities.map((opportunity) => `<article class="wbd-control-opportunity"><span>${esc(opportunity.organizationName)} · ${esc(opportunity.proposalStatus)}</span><h3>${esc(opportunity.title)}</h3><p>${esc(opportunity.problemOrOpportunity)}</p><dl><div><dt>Eenmalig</dt><dd>${euro(opportunity.expectedOneOffRevenue)}</dd></div><div><dt>MRR</dt><dd>${euro(opportunity.expectedMrr)}</dd></div><div><dt>Review</dt><dd>${esc(dateLabel(opportunity.nextReviewAt))}</dd></div></dl>${opportunity.ownerAction ? `<small>Actie: ${esc(opportunity.ownerAction.title)}</small>` : "<small>Geen gekoppelde Owner Action</small>"}</article>`).join("") : '<p class="wbd-control-empty">Nog geen bevestigde open kansen.</p>';
  const exceptions = overview.responsibilityExceptions.length ? overview.responsibilityExceptions.map((item) => `<article class="wbd-control-row"><div><span>${esc(item.organizationName)} · ${esc(item.sourceStatus)}</span><strong>Afspraak vraagt review</strong><p>${item.responsibilities.map(({ description, responsibleParty }) => `${esc(responsibleParty)} · ${esc(description)}`).join("<br>")}</p><small>${item.renewalReviewAt ? `Review ${esc(dateLabel(item.renewalReviewAt))}` : "Geen reviewdatum"}</small></div></article>`).join("") : '<p class="wbd-control-empty">Geen uitzonderingen binnen de bekende afspraken.</p>';
  return `<main class="wbd-owner-workspace wbd-control-home">${topbar}<div class="wbd-control-worklayer"><section class="wbd-control-hero"><div><p class="wbd-owner-eyebrow">Owner control · bevestigde waarheid</p><h1>Home</h1><p>WBD brengt bestaande context terug tot begrijpelijke voorstellen. Jij beslist één keer; Workspace onthoudt en toont daarna de bevestigde werkelijkheid.</p></div><div class="wbd-control-reliability" data-tone="${reliabilityTone}"><span>Betrouwbaarheid</span><strong>${esc(overview.reliability.status)}</strong><small>${overview.reliability.blockers.length} punt${overview.reliability.blockers.length === 1 ? "" : "en"} begrenzen conclusies</small></div></section>
    ${overview.reliability.blockers.length ? `<section class="wbd-control-blockers" aria-label="Betrouwbaarheidsgrenzen">${overview.reliability.blockers.map((blocker) => `<article><strong>${esc(sourceMeaning[blocker.sourceId] ?? "Broninformatie vraagt aandacht")}</strong><p>${blocker.status === "FAILED" ? "De laatste broncontrole is mislukt." : blocker.status === "STALE" ? "De bekende informatie is niet meer actueel genoeg." : "We hebben nog onvoldoende bevestigde informatie voor betrouwbare conclusies."}</p><details><summary>Technische details</summary><small>${esc(blocker.sourceId)} · ${esc(blocker.status)} · ${esc(blocker.coverage)} · ${esc(blocker.impact)}${blocker.lastKnownGoodAt ? ` · laatst goed ${esc(dateLabel(blocker.lastKnownGoodAt))}` : ""}</small></details></article>`).join("")}</section>` : ""}
    <section class="wbd-promotion-section" aria-labelledby="proposal-title"><header><p class="wbd-owner-eyebrow">Gevonden WBD-context</p><h2 id="proposal-title">Voorstellen om vast te leggen</h2><p>Geen voorstel verandert de centrale waarheid voordat jij Bevestigt of Aanpast.</p></header><div class="wbd-promotion-list">${promotionCards(promotions)}</div><p class="wbd-control-message" data-promotion-message role="status"></p></section>
    <section class="wbd-control-panel wbd-organizations" aria-labelledby="organizations-title"><header><p class="wbd-owner-eyebrow">Bevestigde waarheid</p><h2 id="organizations-title">Organisaties</h2></header>${organizationCards(control)}</section>
    <section class="wbd-control-metrics" aria-label="Bedrijfspositie"><article><span>Gecontracteerde MRR</span><strong>${euro(overview.company.confirmedContractedMrr)}</strong></article><article><span>Actieve afspraken</span><strong>${overview.company.activeCommitments}</strong></article><article><span>Recurring Donovan-tijd</span><strong>${overview.company.recurringMinutes === null ? "ONVOLDOENDE BEWIJS" : `${overview.company.recurringMinutes} min`}</strong></article><article><span>MRR / recurring uur</span><strong>${overview.company.mrrPerRecurringHour === null ? "ONVOLDOENDE BEWIJS" : euro(overview.company.mrrPerRecurringHour)}</strong></article></section>
    <div class="wbd-control-columns"><section class="wbd-control-panel"><header><p class="wbd-owner-eyebrow">Management by exception</p><h2>Donovan nodig</h2></header>${attention}</section><section class="wbd-control-panel"><header><p class="wbd-owner-eyebrow">Bevestigd</p><h2>Kansen</h2></header>${opportunities}</section></div>
    <div class="wbd-control-columns"><section class="wbd-control-panel"><header><p class="wbd-owner-eyebrow">Verantwoordelijkheid</p><h2>Alleen uitzonderingen</h2></header>${exceptions}</section><section class="wbd-control-panel wbd-next-best"><header><p class="wbd-owner-eyebrow">Evidence first</p><h2>Beste volgende actie</h2></header>${overview.nextBestAction ? `<strong>${esc(overview.nextBestAction.title)}</strong><p>${esc(overview.nextBestAction.reason)}</p><small>${esc(overview.nextBestAction.priority)}${overview.nextBestAction.dueAt ? ` · ${esc(dateLabel(overview.nextBestAction.dueAt))}` : ""}</small>` : '<p class="wbd-control-empty">ONVOLDOENDE BEWIJS VOOR ÉÉN BESTE VOLGENDE ACTIE</p>'}<a href="${esc(overview.capabilitiesPath)}">Bekijk wat WBD al kan</a></section></div>
    ${recordForms(control)}
    <section class="wbd-control-panel wbd-effort-history"><header><p class="wbd-owner-eyebrow">Traceerbaar</p><h2>Recente inspanning</h2></header>${control.effortObservations.slice().reverse().slice(0, 8).map((effort) => `<article class="wbd-control-row"><div><span>${esc(effort.timeClass)} · ${esc(effort.category)}</span><strong>${effort.minutes} minuten · ${esc(effort.status)}</strong><p>${esc(effort.context ?? "Geen aanvullende context")}</p><small>${esc(dateLabel(effort.capturedAt))}</small></div>${effort.status === "ACTIVE" ? `<form data-void-effort="${esc(effort.id)}"><input name="voidReason" aria-label="Reden correctie" placeholder="Reden voor correctie" required maxlength="500"><button type="submit">Corrigeren</button></form>` : ""}</article>`).join("") || '<p class="wbd-control-empty">Nog geen inspanningswaarnemingen. Afwezigheid wordt niet als nul geïnterpreteerd.</p>'}</section>
    <footer class="wbd-owner-footer"><span>Centrale bron · revisie ${control.revision}</span><span>Release ${esc(control.releaseId)}</span><span>Geen browserdata geïmporteerd.</span></footer></div></main>`;
}

function refs(value: FormDataEntryValue | null): string[] { return String(value ?? "").split(/[\n,]/gu).map((part) => part.trim()).filter(Boolean); }
function isoDate(value: FormDataEntryValue | null): string | null { const raw = String(value ?? "").trim(); return raw ? `${raw}T00:00:00.000Z` : null; }
function amount(value: FormDataEntryValue | null): number | null { const raw = String(value ?? "").trim(); return raw === "" ? null : Number(raw); }

function formPayload(recordType: ControlRecordType, fields: FormData): Record<string, unknown> {
  if (recordType === "organizations") return { name: fields.get("name"), relationshipType: fields.get("relationshipType"), status: fields.get("status"), reviewedAt: isoDate(fields.get("reviewedAt")), sourceRefs: refs(fields.get("sourceRefs")) };
  if (recordType === "opportunities") return { organizationId: fields.get("organizationId"), title: fields.get("title"), problemOrOpportunity: fields.get("problemOrOpportunity"), status: fields.get("status"), valueType: fields.get("valueType"), expectedOneOffRevenue: amount(fields.get("expectedOneOffRevenue")), expectedMrr: amount(fields.get("expectedMrr")), proposalStatus: fields.get("proposalStatus"), evidenceRefs: refs(fields.get("sourceRefs")), nextReviewAt: isoDate(fields.get("nextReviewAt")), ownerActionId: null };
  if (recordType === "commitments") return { organizationId: fields.get("organizationId"), status: fields.get("status"), contractedMrr: amount(fields.get("contractedMrr")), startsAt: isoDate(fields.get("startsAt")), endsAt: isoDate(fields.get("endsAt")), renewalReviewAt: isoDate(fields.get("renewalReviewAt")), responsibilities: [{ description: fields.get("responsibilityDescription"), responsibleParty: fields.get("responsibleParty") }], sourceRefs: refs(fields.get("sourceRefs")) };
  if (recordType === "actions") { const [subjectType, subjectId] = String(fields.get("subject") ?? "|").split("|"); return { subjectType, subjectId, title: fields.get("title"), reasonDonovanNeeded: fields.get("reasonDonovanNeeded"), status: "OPEN", priority: fields.get("priority"), dueAt: isoDate(fields.get("dueAt")), sourceRefs: refs(fields.get("sourceRefs")) }; }
  return { organizationId: fields.get("organizationId"), serviceCommitmentId: null, timeClass: fields.get("timeClass"), category: fields.get("category"), minutes: Number(fields.get("minutes")), context: fields.get("context") || null, capturedAt: new Date().toISOString(), sourceRefs: refs(fields.get("sourceRefs")), correctionOf: null };
}

function promotionAdjustments(proposal: PromotionProposal, fields: FormData): Record<string, unknown> {
  const result: Record<string, unknown> = {};
  for (const field of proposal.allowedAdjustments) {
    const value = fields.get(field);
    if (value !== null && String(value).trim() !== "") result[field] = new Set(["nextReviewAt", "dueAt"]).has(field) ? isoDate(value) : value;
  }
  if (proposal.allowedAdjustments.includes("dueAt") && fields.has("dueAt") && !fields.get("dueAt")) result.dueAt = null;
  return result;
}

export function bindControlHome(app: HTMLDivElement, control: ControlView, promotions: PromotionView, handlers: { create: (recordType: ControlRecordType, payload: Record<string, unknown>) => Promise<void>; patch: (recordType: ControlRecordType, recordId: string, payload: Record<string, unknown>) => Promise<void>; review: (proposalId: string, decision: "ACCEPT" | "ADJUST" | "REJECT", adjustments?: Record<string, unknown>) => Promise<void> }): void {
  const message = app.querySelector<HTMLElement>("[data-control-message]");
  const proposalMessage = app.querySelector<HTMLElement>("[data-promotion-message]");
  const run = async (operation: () => Promise<void>, pending: string, target = message): Promise<void> => { if (target) target.textContent = pending; try { await operation(); } catch (cause) { if (target) target.textContent = cause instanceof Error ? cause.message : "De centrale wijziging is mislukt."; } };
  app.querySelectorAll<HTMLButtonElement>("[data-effort-minutes]").forEach((button) => button.addEventListener("click", () => { const form = button.closest("form")!; form.querySelectorAll<HTMLButtonElement>("[data-effort-minutes]").forEach((candidate) => candidate.setAttribute("aria-pressed", String(candidate === button))); form.querySelector<HTMLInputElement>('input[name="minutes"]')!.value = button.dataset.effortMinutes!; }));
  app.querySelectorAll<HTMLFormElement>("[data-control-form]").forEach((form) => form.addEventListener("submit", (event) => { event.preventDefault(); const recordType = form.dataset.controlForm as ControlRecordType; void run(() => handlers.create(recordType, formPayload(recordType, new FormData(form))), "Centrale waarheid wordt vastgelegd…"); }));
  app.querySelectorAll<HTMLButtonElement>("[data-complete-action]").forEach((button) => button.addEventListener("click", () => { const action = control.ownerActions.find(({ id }) => id === button.dataset.completeAction); if (action) void run(() => handlers.patch("actions", action.id, { status: "DONE", expectedRecordRevision: action.revision }), "Actie wordt afgerond…"); }));
  app.querySelectorAll<HTMLFormElement>("[data-void-effort]").forEach((form) => form.addEventListener("submit", (event) => { event.preventDefault(); const effort = control.effortObservations.find(({ id }) => id === form.dataset.voidEffort); if (effort) void run(() => handlers.patch("effort-observations", effort.id, { status: "VOIDED", voidReason: new FormData(form).get("voidReason"), expectedRecordRevision: effort.revision }), "Waarneming wordt traceerbaar gecorrigeerd…"); }));
  app.querySelectorAll<HTMLButtonElement>("[data-promotion-toggle]").forEach((button) => button.addEventListener("click", () => { const form = app.querySelector<HTMLFormElement>(`[data-promotion-adjust="${button.dataset.promotionToggle}"]`); if (form) form.hidden = !form.hidden; }));
  app.querySelectorAll<HTMLButtonElement>("[data-promotion-review]").forEach((button) => button.addEventListener("click", () => { const proposalId = button.dataset.promotionReview!; const decision = button.dataset.decision as "ACCEPT" | "REJECT"; void run(() => handlers.review(proposalId, decision), decision === "REJECT" ? "Voorstel wordt afgewezen…" : "Bevestiging wordt veilig vastgelegd…", proposalMessage); }));
  app.querySelectorAll<HTMLFormElement>("[data-promotion-adjust]").forEach((form) => form.addEventListener("submit", (event) => { event.preventDefault(); const proposal = promotions.proposals.find(({ id }) => id === form.dataset.promotionAdjust); if (proposal) void run(() => handlers.review(proposal.id, "ADJUST", promotionAdjustments(proposal, new FormData(form))), "Aangepaste betekenis wordt veilig vastgelegd…", proposalMessage); }));
}
